
trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: UseDotNet@2
  inputs:
    version: 8.0.x
    packageType: 'sdk'
    #includePreviewVersions: true
  

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dotnet --list-sdks'