
trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: UseDotNet@2
  inputs:
    version: 8.x
    includePreviewVersions: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dotnet --list-sdks'