name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  bash:
    name: ${{ matrix.os }} / bash / ${{ matrix.command }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019", "windows-2022"]
        command: ["cargo --help", "rustup --help", "python --help", "git --help"]

    steps:
    - run: Set-MpPreference -DisableRealtimeMonitoring $true
      shell: powershell
    - run: Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\System' -Name 'EnableSmartScreen' -Type DWord -Value 0
      shell: powershell  
    - run: time ${{ matrix.command }}
      shell: bash
    - run: time ${{ matrix.command }}
      shell: bash

  pwsh:
    name: ${{ matrix.os }} / pwsh / ${{ matrix.command }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019", "windows-2022"]
        command: ["cargo --help", "rustup --help", "python --help", "git --help"]

    steps:
    - run: Set-MpPreference -DisableRealtimeMonitoring $true
      shell: pwsh
    - run: (Measure-Command{ ${{ matrix.command }} }).TotalSeconds
      shell: pwsh
    - run: (Measure-Command{ ${{ matrix.command }} }).TotalSeconds
      shell: pwsh

  powershell:
    name: ${{ matrix.os }} / powershell / ${{ matrix.command }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019", "windows-2022"]
        command: ["cargo --help", "rustup --help", "python --help", "git --help"]

    steps:
    - run: Set-MpPreference -DisableRealtimeMonitoring $true
      shell: powershell
    - run: (Measure-Command{ ${{ matrix.command }} }).TotalSeconds
      shell: powershell
    - run: (Measure-Command{ ${{ matrix.command }} }).TotalSeconds
      shell: powershell
